language: ruby
cache: bundler
rvm:
  - 2.3.0
git:
  submodules: false
addons:
  code_climate:
    repo_token: 3a37b06b904d7cd224d38b486334dd1c77c6eedf5efc96173531a470e9b8c8ea
env:
  global:
    - RACK_ENV=test
branches:
  only:
    - master
install:
  - bundle install
script:
  - ./scripts/setupdb.sh
  - rake test --trace
after_success:
  - bundle exec codeclimate-test-reporter
deploy:
  provider: heroku
  api_key: "9951e24c-b489-48fe-8a60-b325e8d850dd"
  app: wulf-usa
  run: "rake db:migrate --trace"