language: ruby
rvm:
- 2.4.0
git:
  submodules: false
addons:
  code_climate:
    repo_token: 3a37b06b904d7cd224d38b486334dd1c77c6eedf5efc96173531a470e9b8c8ea
services:
- postgresql
- redis-server
- memcached
env:
  global:
  - RACK_ENV=test
  - PORT=8080
  - APP_SUPER_UNAME=testuser
  - APP_SUPER_PASSWD=testpassword
  - REDIS_URL=redis://localhost:6379
  - MEMCACHIER_SERVERS=localhost:11211
  matrix:
  - TEST_TYPE=unit
  - TEST_TYPE=integration
  - TEST_TYPE=performance
branches:
  only:
  - master
install:
- gem update --system
- gem cert --add <(curl -Ls https://raw.githubusercontent.com/thesp0nge/dawnscanner/master/certs/paolo_at_dawnscanner_dot_org.pem)
- bundle install --jobs=3 --retry=3
- sass --update public/src/css:public/src/css
- "./scripts/setupdb.sh"
script:
- foreman start --formation web=1, worker=2 &
- sleep 15
- rspec --tag $TEST_TYPE --format doc --color
- dawn --exit-on-warn --sinatra $TRAVIS_BUILD_DIR
- bundle-audit check --update
- rubocop -EDLR
after_success:
- "./scripts/submitcoverage.sh"
deploy:
  provider: heroku
  buildpack: ruby
  api_key:
    secure: YdvHMsHoWPfqEcJQazbYCyYKKzzif0dKu+gxQobE3phXz5eQR5W+OvY0SZay/gg5WobPlI5hL9+fuA7qgYIFjg7H8GZbfXoyBUA7WE8cWScha6d8C3YxUR33Dxokbt8TzWCKuGMSk6DN2aPpoFDQMrGskpivEbRnn+0p9T5aAnSahNDbUTUaeOExV/ObZyWMJryUG2d/p88uctajg5067NBbzd/zuipD9ksm7r/IdKNIHRVltCyrxUrj7KEwvb9U6+IwwWjSNgcUGT7Exqiz17RQUM+fFLQZZoZAx1Ysbp22Hj2ILTNTCn7uOxlMoigUumxsxdhmtFxRRnejT6ODk2b9WLH+bx/aw9+y2+uK4KeXWW97c4fZhHRs6517ytuf4NBvikCXjK/cQA1FUQc8kBk3+zEgWMoV+DKw4j8YylORALUKtjepKpMWEZUd3Ol+c39jfG3DoFy4E91cggPDl5NC7Ll1zbDT2dzVk3+Uo2NZ3utXMNIJcbqks7qkh4Dv3lYQobwLG2vh8Q9797GCdzmmmASZa1oeXXxBPCX9xXJIeL8SeEyx9P9+Qys0szgt47IG3ZN7e9vJpB8EMGnqvy2U1fTrRqSsyaQMTLIVmaKx0Fz5Olqn8ZpVy0Vb1oMVkkQtbRWLYsl2gEzFGFqM68Q76QDHimGaoEMXv9HATWU=
  app: wulf-usa
  skip_cleanup: true
  run: rake db:migrate
  on:
    condition: "$TEST_TYPE = integration"
