development:
  adapter: postgresql
  database: wulfusa
  host: localhost
  username: ubuntu
  password: test
test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
production:
  adapter: postgresql